site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

pages:
- Overview: 'index.md'
- Specification:
    - '1.0': 'specification/1.0.md'
- Hooks:
    - 'Predefined CDS Hooks' : 'hook_catalog/index.md'
    - 'patient-view' : 'hook_catalog/patient-view.md'
    - 'medication-prescribe' : 'hook_catalog/medication-prescribe.md'
    - 'order-review' : 'hook_catalog/order-review.md'
- Examples: 'examples.md'
- Community: 'community.md'

repo_url: 'https://github.com/cds-hooks/docs'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
