site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

pages:
- Overview: 'index.md'
- Specification:
    - '1.0': 'specification/1.0.md'
- Hooks:
    - 'Hooks' : 'hooks/index.md'
    - 'new-hook-template' : 'hooks/template.md'
    - 'patient-view' : 'hooks/patient-view.md'
    - 'medication-prescribe' : 'hooks/medication-prescribe.md'
    - 'order-review' : 'hooks/order-review.md'
    - 'result-review' : 'hooks/result-review.md'
- Quick Start: 'quickstart.md'
- Examples: 'examples.md'
- Community: 'community.md'

repo_url: 'https://github.com/cds-hooks/docs'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
